### ISSUE TITLE
Using with serverless-offline

### ISSUE THREAD

**Issue by chrisrothwell** [JamesKyburz/aws-lambda-http-server#10]
Hi,
This package is exactly what I need, thanks so much for making it available!
I'm having a problem testing it with sls-offline.
Is there any reason why this wouldn't work with sls offline?
Below is the error that I'm getting.  Thanks so much in advance for any help!

{
    "errorMessage": "Uncaught error in your 'proxy' handler",
    "errorType": "TypeError",
    "stackTrace": [
        "TypeError: Cannot read property 'replace' of undefined",
        "at module.exports (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\aws-lambda-create-request-response\\src\\index.js:17:39)",
        "at module.exports (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\aws-lambda-http-server\\src\\index.js:12:24)",
        "at handler (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\serverless-offline\\src\\index.js:909:25)",
        "at Object.internals.handler (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\handler.js:96:36)",
        "at request._protect.run (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\handler.js:30:23)",
        "at module.exports.internals.Protect.internals.Protect.run (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\protect.js:64:5)",
        "at exports.execute (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\handler.js:24:22)",
        "at each (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\request.js:384:16)",
        "at iterate (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\items\\lib\\index.js:36:13)",
        "at done (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\items\\lib\\index.js:28:25)",
        "at internals.Auth.payload (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\auth.js:223:16)",
        "at each (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\request.js:384:16)",
        "at iterate (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\items\\lib\\index.js:36:13)",
        "at done (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\items\\lib\\index.js:28:25)",
        "at internals.payload (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\route.js:393:16)",
        "at each (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\request.js:384:16)",
        "at iterate (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\items\\lib\\index.js:36:13)",
        "at done (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\items\\lib\\index.js:28:25)",
        "at module.exports.internals.Auth.internals.Auth._authenticate (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\auth.js:210:16)",
        "at internals.Auth.authenticate (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\auth.js:202:17)",
        "at each (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\request.js:384:16)",
        "at iterate (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\items\\lib\\index.js:36:13)",
        "at done (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\items\\lib\\index.js:28:25)",
        "at internals.state (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\route.js:357:16)",
        "at each (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\request.js:384:16)",
        "at iterate (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\items\\lib\\index.js:36:13)",
        "at Object.exports.serial (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\items\\lib\\index.js:39:9)",
        "at internals.Request._lifecycle (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\request.js:387:11)",
        "at internals.Request._execute (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\request.js:302:21)",
        "at Domain.request._protect.enter (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\connection.js:261:25)",
        "at Domain.run (domain.js:242:14)",
        "at module.exports.internals.Protect.internals.Protect.enter (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\protect.js:80:17)",
        "at Server.<anonymous> (C:\\Users\\christop\\Documents\\Stuff\\Digital\\Projects\\testlambdaserver\\node_modules\\hapi\\lib\\connection.js:259:30)",
        "at emitTwo (events.js:126:13)",
        "at Server.emit (events.js:214:7)",
        "at parserOnIncoming (_http_server.js:619:12)"
    ],
    "offlineInfo": "If you believe this is an issue with the plugin please submit it, thanks. https://github.com/dherault/serverless-offline/issues"
}

**Comment by JamesKyburz** [comment]
👍 At a glance I think the problem is that serverless offline doesn't set event.requestContext.path which api gateway does.

When running our services locally we just run the vanilla http server code, and haven't used any serverless tools :) 

I can probably add a fullback for path if requestContext.path isn't set (I think api gateway adds the path in more than one place...)
